// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitManagement.Data;

#nullable disable

namespace VisitManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 29, 11, 5, 37, 753, DateTimeKind.Local).AddTicks(9473),
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            IsActive = true,
                            PhoneNumber = "+1-555-0100",
                            Role = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 12, 29, 11, 5, 37, 753, DateTimeKind.Local).AddTicks(9476),
                            Email = "jane.smith@example.com",
                            FullName = "Jane Smith",
                            IsActive = true,
                            PhoneNumber = "+1-555-0101",
                            Role = "Sales Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 12, 29, 11, 5, 37, 753, DateTimeKind.Local).AddTicks(9478),
                            Email = "bob.johnson@example.com",
                            FullName = "Bob Johnson",
                            IsActive = true,
                            PhoneNumber = "+1-555-0102",
                            Role = "Team Lead"
                        });
                });

            modelBuilder.Entity("VisitManagement.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DebitingProjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("IntimationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyMessages")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LevelOfVisitors")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfAttendees")
                        .HasColumnType("int");

                    b.Property<string>("OpportunityDetails")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OpportunityType")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SalesSpoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SalesStage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("ServiceScope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TcvMnUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeOfVisit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Vertical")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitDuration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisitLead")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VisitStatus")
                        .HasColumnType("int");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VisitorsName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountName = "Acme Corporation",
                            CreatedDate = new DateTime(2025, 12, 29, 11, 5, 37, 753, DateTimeKind.Local).AddTicks(9616),
                            DebitingProjectId = "PROJ-001",
                            IntimationDate = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KeyMessages = "Demonstrate cloud capabilities and cost savings",
                            LevelOfVisitors = "C-Level",
                            Location = "New York",
                            NumberOfAttendees = 5,
                            OpportunityDetails = "New cloud infrastructure project",
                            OpportunityType = 0,
                            Remarks = "Important strategic meeting",
                            SalesSpoc = "John Doe",
                            SalesStage = "Proposal",
                            SerialNumber = 1,
                            ServiceScope = "Cloud migration and consulting",
                            Site = "Acme HQ",
                            TcvMnUsd = 1.5m,
                            TypeOfVisit = "Client Meeting",
                            Vertical = "Technology",
                            VisitDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitDuration = "1 Day",
                            VisitLead = "Capability",
                            VisitStatus = 0,
                            VisitType = "On-site",
                            VisitorsName = "Mark Williams, Sarah Davis"
                        },
                        new
                        {
                            Id = 2,
                            AccountName = "Global Bank Ltd",
                            CreatedDate = new DateTime(2025, 12, 29, 11, 5, 37, 753, DateTimeKind.Local).AddTicks(9622),
                            DebitingProjectId = "PROJ-002",
                            IntimationDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KeyMessages = "Showcase platform scalability and security features",
                            LevelOfVisitors = "VP Level",
                            Location = "London",
                            NumberOfAttendees = 8,
                            OpportunityDetails = "Digital transformation initiative",
                            OpportunityType = 1,
                            Remarks = "Follow-up demo session",
                            SalesSpoc = "Jane Smith",
                            SalesStage = "Negotiation",
                            SerialNumber = 2,
                            ServiceScope = "Digital banking platform development",
                            Site = "Global Bank Office",
                            TcvMnUsd = 3.2m,
                            TypeOfVisit = "Technical Demo",
                            Vertical = "Finance",
                            VisitDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitDuration = "4 Hours",
                            VisitLead = "Sales",
                            VisitStatus = 1,
                            VisitType = "Virtual",
                            VisitorsName = "Peter Brown, Lisa Anderson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
